14:05:58.074031 INFO [otestpointd/application] commandline: otestpointd -d -l 3 -f /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/5/var/log/otestpointd.log --pidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/5/var/run/otestpointd.pid --uuidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/5/var/run/otestpointd.uuid otestpointd5.xml 
14:05:58.074075 INFO [otestpointd/application] uuid: 079595d7-be76-43ee-9168-31309a3aaba4
14:05:58.088686 INFO [otestpointd] discovery service listening on tcp://10.99.0.5:8881
14:05:58.552583 INFO [otestpoint-probe/node-5/0/manager] available probes: EMANE.PhysicalLayer.Counters.General EMANE.PhysicalLayer.Tables.Events EMANE.PhysicalLayer.Tables.Status
14:05:58.553926 INFO [otestpoint-probe/node-5/1/manager] available probes: EMANE.RFPipe.Counters.General EMANE.RFPipe.Tables.Events EMANE.RFPipe.Tables.Neighbor EMANE.RFPipe.Tables.Status
14:05:58.555134 INFO [otestpoint-probe/node-5/2/manager] available probes: EMANE.VirtualTransport.Counters.General EMANE.VirtualTransport.Tables.Events EMANE.VirtualTransport.Tables.Status
14:05:58.556441 ERROR [otestpointd/node-5/0/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

14:05:58.556998 ERROR [otestpointd/node-5/1/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

14:05:58.557784 ERROR [otestpointd/node-5/2/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

