14:06:00.120554 INFO [otestpointd/application] commandline: otestpointd -d -l 3 -f /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/7/var/log/otestpointd.log --pidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/7/var/run/otestpointd.pid --uuidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/7/var/run/otestpointd.uuid otestpointd7.xml 
14:06:00.120601 INFO [otestpointd/application] uuid: 4e821787-a61e-4ba9-ab63-7debd525738f
14:06:00.164751 INFO [otestpointd] discovery service listening on tcp://10.99.0.7:8881
14:06:00.628325 INFO [otestpoint-probe/node-7/0/manager] available probes: EMANE.PhysicalLayer.Counters.General EMANE.PhysicalLayer.Tables.Events EMANE.PhysicalLayer.Tables.Status
14:06:00.629632 INFO [otestpoint-probe/node-7/1/manager] available probes: EMANE.RFPipe.Counters.General EMANE.RFPipe.Tables.Events EMANE.RFPipe.Tables.Neighbor EMANE.RFPipe.Tables.Status
14:06:00.631016 INFO [otestpoint-probe/node-7/2/manager] available probes: EMANE.VirtualTransport.Counters.General EMANE.VirtualTransport.Tables.Events EMANE.VirtualTransport.Tables.Status
14:06:00.632247 ERROR [otestpointd/node-7/0/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

14:06:00.633291 ERROR [otestpointd/node-7/1/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

14:06:00.633971 ERROR [otestpointd/node-7/2/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 195, in start
    raise ProbeException("unable to connect to %s:%d" % (self._address,self._port))

ProbeException: unable to connect to localhost:47000

