14:06:03.251023 INFO [otestpointd/application] commandline: otestpointd -d -l 3 -f /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/10/var/log/otestpointd.log --pidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/10/var/run/otestpointd.pid --uuidfile /home/ubuntu/Desktop/emane-tutorial/dlepmaban/persist/10/var/run/otestpointd.uuid otestpointd10.xml 
14:06:03.251094 INFO [otestpointd/application] uuid: 08ae958d-db50-4cd5-bdc8-a10ab1a6608d
14:06:03.258165 INFO [otestpointd] discovery service listening on tcp://10.99.0.10:8881
14:06:03.768018 INFO [otestpoint-probe/node-10/0/manager] available probes: EMANE.PhysicalLayer.Counters.General EMANE.PhysicalLayer.Tables.Events EMANE.PhysicalLayer.Tables.Status
14:06:03.769406 INFO [otestpoint-probe/node-10/1/manager] available probes: EMANE.RFPipe.Counters.General EMANE.RFPipe.Tables.Events EMANE.RFPipe.Tables.Neighbor EMANE.RFPipe.Tables.Status
14:06:03.770637 INFO [otestpoint-probe/node-10/2/manager] available probes: EMANE.VirtualTransport.Counters.General EMANE.VirtualTransport.Tables.Events EMANE.VirtualTransport.Tables.Status
14:06:15.000970 ERROR [otestpoint-probe/node-10/2/manager] probe error: Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 244, in probe
    if response.type == remotecontrolportapi_pb2.Response.TYPE_RESPONSE_QUERY:

AttributeError: 'NoneType' object has no attribute 'type'

14:06:15.000970 ERROR [otestpoint-probe/node-10/1/manager] probe error: Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 244, in probe
    if response.type == remotecontrolportapi_pb2.Response.TYPE_RESPONSE_QUERY:

AttributeError: 'NoneType' object has no attribute 'type'

14:06:15.000973 ERROR [otestpoint-probe/node-10/0/manager] probe error: Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 244, in probe
    if response.type == remotecontrolportapi_pb2.Response.TYPE_RESPONSE_QUERY:

AttributeError: 'NoneType' object has no attribute 'type'

