09:45:58.291097 INFO [otestpointd/application] commandline: otestpointd -d -l 3 -f /home/ubuntu/Desktop/emane-tutorial/23aliakim/persist/host/var/log/otestpointd5.log --pidfile /home/ubuntu/Desktop/emane-tutorial/23aliakim/persist/host/var/run/otestpointd5.pid --uuidfile /home/ubuntu/Desktop/emane-tutorial/23aliakim/persist/host/var/run/otestpointd5.uuid host-otestpointd5.xml 
09:45:58.291129 INFO [otestpointd/application] uuid: dae1dfdd-0f71-4266-bf9e-c51f9f0ae1ee
09:45:58.306347 INFO [otestpointd] discovery service listening on tcp://127.0.0.1:8885
09:45:59.630924 INFO [otestpoint-probe/node-5/0/manager] available probes: EMANE.PhysicalLayer.Counters.General EMANE.PhysicalLayer.Tables.Events EMANE.PhysicalLayer.Tables.Status
09:45:59.639700 INFO [otestpoint-probe/node-5/1/manager] available probes: EMANE.RFPipe.Counters.General EMANE.RFPipe.Tables.Events EMANE.RFPipe.Tables.Neighbor EMANE.RFPipe.Tables.Status
09:45:59.642910 ERROR [otestpointd/node-5/1/container] Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/otestpoint/emane/probebase.py", line 222, in start
    raise ProbeException("unable to determine build id")

ProbeException: unable to determine build id

09:55:46.640999 INFO [otestpointd/application] shutdown
